### ISSUE TITLE
no module named obswebsocket

### ISSUE THREAD

**Issue by johnwry** [tvanyo/obsPPTXwithPython#2]
Traceback (most recent call last):
  File "obsPPTX.py", line 3, in <module>
    import obswebsocket
ImportError: No module named obswebsocket

**Comment by johnwry** [comment]
using python3 corrected this. 
Then I got an error saying No module named 'pygame' so I installed it. 

Now I am getting this error: 
  File "/usr/local/lib/python3.9/site-packages/obswebsocket/core.py", line 73, in connect
    raise exceptions.ConnectionFailure(str(e))
obswebsocket.exceptions.ConnectionFailure: [Errno 61] Connection refused

**Comment by johnwry** [comment]
ok. got it... I had failed to install the websockets plugin for OBS. 
Now to find the commands....

**Comment by johnwry** [comment]
So,  I start up my presentation in window mode, run the obsPTTX.py script and this this then changes obs to the default screen. I cannot however, get it two where I scroll through PPT and make OBS change scenes...

**Comment by tvanyo** [comment]
Are you trying to use obsPPTX.py or the three standalone scripts?

Did you note this?

> You need to add "OBS:" to the notes section, just like in Scott's implmentation. You should have the presentation in Slide Show view for this to work out of the gate. Just like Scott's, you'll have a terminal open to run.

The standalone scripts are intended to eliminate the need for pygame, but they have slightly more overhead in establishing the websocket connection every time they are run. In my limited experience, there really isn't a noticeable timing hit doing this.

**Comment by johnwry** [comment]
ok. I just don’t know how to implement them. What do I need to do? 
Also, I am trying to implement this from one Mac playing PowerPoint to another pc that has obs. Possible? This will be amazing if I can get it to work! Total game changer!!!

**Comment by johnwry** [comment]
When running the individual scripts they make powerpoint play forward/backward/start but there's no change in OBS.

**Comment by tvanyo** [comment]
This should be done with PowerPoint and OBS on the same Mac. I can't help you get this running across machines. 

The stand-alone scripts require an app like [Keysmith](www.Keysmith.app) or [Keyboard Maestro](www.keyboardmaestro.com) to get a registered keystroke to run the appropriate script (such as Alt+R to advance the slide deck). I'd point you to those app manuals on getting a keystroke to launch a python script.

**Comment by johnwry** [comment]
I have it going to the default scene on OBS. How do I label the notes so that it goes to other scenes?

**Comment by tvanyo** [comment]
You need to put **OBS:foo** in the notes, replacing **foo** with whatever scene you want. This is in the readme.

**Comment by johnwry** [comment]
So, I've got this sort of working over the network (changed localhost to IP address). 
It actually works...sometimes...the behaviour is sporadic, and I can't figure out why.  If I begin with OBS:scene1 then it seems to switch ok between  that scene and the default scene (DefaultPPTX). But if I set the first slide empy or labeled OBS:DefaultPPTX then it never goes to another scene. I must be doing something wrong. Super excited this is so close working!

**Comment by johnwry** [comment]
actually, to clarify, this was also happening while on the one machine as well.

**Comment by tvanyo** [comment]
Can you attach a powerpoint deck that isn't working?

**Comment by johnwry** [comment]
Thanks for checking this out...

**Comment by tvanyo** [comment]
Sorry, didn't see an attachment.

**Comment by tvanyo** [comment]
@johnwry You need to attached the file by replying inside github. If you attached via email it didn't get to me.

**Comment by johnwry** [comment]
Dang it, sorry. Here it is..
https://www.dropbox.com/s/owrehtkcdus78l9/Apocalipsis%20%281-11%29%20p124%20V-2.pptx?dl=1

**Comment by johnwry** [comment]
Ok. Let me share my findings. 

Using transitions between slides may cause sporadic behaviour. 
Also, using OBS:{default} does not work, just leave it blank for the default scene as configured in the *.py file.

**Comment by johnwry** [comment]
Todd, 

I am super excited! I’ve got your script running!! I have it working so that I know the glitches enough to work with it. 
This is great! Thanks so much for your work on this!! 

Regards,
John

**Comment by readeral** [comment]
@johnwry so I'm similarly having trouble - what did you discover to get this working?

@tvanyo Hi Todd, just picking up from this issue, I'm able to run the script and get it to move to the default scene, but beyond that the script stops listening for keyboard input. I know this because when I first open the script it's perfectly happy to receive a q command (as per line 85 of obsPPTX.py) but if I head over to powerpoint and use the arrow keys (or use q), and come back to pygame I need to hit ctrl-C to restart, as q does nothing.

Just in case it helps, I'm using Python 3.x

Is there something I'm missing here?

EDIT: AHHH Ok I get it. The python runtime has to be the 'app' in focus. Sorry, just had to look at the code a little closer haha >.<

**Comment by readeral** [comment]
Maybe I need to look into applescript permissions or something

**Comment by tvanyo** [comment]
@readeral, glad you got it working. I should put that in the documentation.

I would recommend looking at what I called the "One Trick Pony" scripts. These run without the need for pygame, which does require the python script to be the focus. They do require, however, you to have an app like [Alfred](https://www.alfredapp.com/) (which I would highly recommend), [Keyboard Maestro](https://www.keyboardmaestro.com/), or [Keysmith](https://www.keysmith.app/).
